/**
 * rom_reader.c - Runtime ROM file reader for PC port
 *
 * Loads the user's baserom.z64 into memory at startup and provides functions
 * to read from it. The ROM offset lookup table (generated by gen_rom_offsets.py)
 * maps overlay stub symbol addresses to their actual ROM file offsets.
 *
 * This allows dma_copy() and nuPiReadRom() to work correctly on PC by reading
 * from the loaded ROM image instead of N64 cartridge hardware.
 */

#include "common.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ROM image loaded at runtime
static u8* sRomImage = NULL;
static u32 sRomSize = 0;

// Lookup table generated by tools/pc/gen_rom_offsets.py
typedef struct {
    const void* symbol_addr;
    u32 rom_offset;
} RomSymbolEntry;

extern RomSymbolEntry gRomOffsetTable[];
extern const u32 gRomOffsetTableSize;

// Whether the table has been sorted (done once on first lookup)
static s32 sTableSorted = FALSE;

static int rom_entry_compare(const void* a, const void* b) {
    const RomSymbolEntry* ea = (const RomSymbolEntry*)a;
    const RomSymbolEntry* eb = (const RomSymbolEntry*)b;
    if (ea->symbol_addr < eb->symbol_addr) return -1;
    if (ea->symbol_addr > eb->symbol_addr) return 1;
    return 0;
}

static void ensure_table_sorted(void) {
    if (!sTableSorted) {
        qsort(gRomOffsetTable, gRomOffsetTableSize, sizeof(RomSymbolEntry), rom_entry_compare);
        sTableSorted = TRUE;
    }
}

/**
 * Look up the ROM file offset for an overlay stub symbol address.
 * Returns the ROM offset, or 0xFFFFFFFF if not found.
 */
u32 pc_rom_lookup_offset(const void* symbol_addr) {
    ensure_table_sorted();

    // Binary search
    s32 lo = 0, hi = (s32)gRomOffsetTableSize - 1;
    while (lo <= hi) {
        s32 mid = (lo + hi) / 2;
        if (gRomOffsetTable[mid].symbol_addr == symbol_addr) {
            return gRomOffsetTable[mid].rom_offset;
        } else if (gRomOffsetTable[mid].symbol_addr < symbol_addr) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return 0xFFFFFFFF;
}

/**
 * Load baserom.z64 from disk into memory.
 * Searches for the file in several locations relative to the executable.
 * Returns TRUE on success, FALSE if the ROM file is not found.
 */
s32 pc_rom_init(void) {
    const char* search_paths[] = {
        "ver/us/baserom.z64",
        "baserom.z64",
        "../ver/us/baserom.z64",
        "../baserom.z64",
    };

    FILE* f = NULL;
    const char* found_path = NULL;
    for (u32 i = 0; i < sizeof(search_paths) / sizeof(search_paths[0]); i++) {
        f = fopen(search_paths[i], "rb");
        if (f) {
            found_path = search_paths[i];
            break;
        }
    }

    if (!f) {
        fprintf(stderr, "[ROM] WARNING: baserom.z64 not found. DMA loads will return zeros.\n");
        fprintf(stderr, "[ROM] Place your Paper Mario (US) ROM as ver/us/baserom.z64\n");
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    sRomSize = (u32)ftell(f);
    fseek(f, 0, SEEK_SET);

    sRomImage = (u8*)malloc(sRomSize);
    if (!sRomImage) {
        fprintf(stderr, "[ROM] Failed to allocate %u bytes for ROM image\n", sRomSize);
        fclose(f);
        return FALSE;
    }

    u32 bytesRead = (u32)fread(sRomImage, 1, sRomSize, f);
    fclose(f);

    if (bytesRead != sRomSize) {
        fprintf(stderr, "[ROM] Read only %u of %u bytes\n", bytesRead, sRomSize);
        free(sRomImage);
        sRomImage = NULL;
        sRomSize = 0;
        return FALSE;
    }

    fprintf(stderr, "[ROM] Loaded %s (%u bytes / %.1f MB)\n",
            found_path, sRomSize, sRomSize / (1024.0f * 1024.0f));
    return TRUE;
}

/**
 * Read bytes from the loaded ROM image at a given file offset.
 * Used by nuPiReadRom() on PC.
 */
void pc_rom_read(u32 rom_offset, void* dest, u32 size) {
    if (sRomImage && rom_offset + size <= sRomSize) {
        memcpy(dest, sRomImage + rom_offset, size);
    } else {
        memset(dest, 0, size);
    }
}

/**
 * Check if ROM is loaded.
 */
s32 pc_rom_is_loaded(void) {
    return sRomImage != NULL;
}

/**
 * Compute the ROM byte size of a segment given its ROM_START and ROM_END
 * stub symbol pointers. On PC, the stub addresses have no meaningful
 * distance, so we look up both offsets from the table.
 * Returns 0 if either symbol is unknown.
 */
u32 pc_rom_segment_size(const void* rom_start, const void* rom_end) {
    u32 startOfs = pc_rom_lookup_offset(rom_start);
    u32 endOfs   = pc_rom_lookup_offset(rom_end);
    if (startOfs != 0xFFFFFFFF && endOfs != 0xFFFFFFFF && endOfs > startOfs) {
        return endOfs - startOfs;
    }
    return 0;
}

void pc_rom_debug_dma(u32 start, u32 end, u32 len) {
    fprintf(stderr, "[DMA] ROM 0x%06X-0x%06X (%u bytes)\n", start, end, len);
    fflush(stderr);
}

void pc_rom_shutdown(void) {
    if (sRomImage) {
        free(sRomImage);
        sRomImage = NULL;
        sRomSize = 0;
    }
}
