#!/usr/bin/env python3
"""
Generate a C lookup table mapping overlay stub symbol addresses to ROM file offsets.

Reads the splat.yaml segment definitions to extract ROM addresses for each named
segment, then generates rom_offsets.c with a sorted table that dma_copy() uses at
runtime to translate stub pointer addresses into baserom.z64 file offsets.

Usage:
    python tools/pc/gen_rom_offsets.py

Output:
    src/pc/gen/rom_offsets.c
"""

import os
import sys
import yaml
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
SPLAT_YAML = PROJECT_ROOT / "ver" / "us" / "splat.yaml"
OVERLAY_STUBS = PROJECT_ROOT / "src" / "pc" / "platform" / "overlay_stubs.c"
OUTPUT_FILE = PROJECT_ROOT / "src" / "pc" / "gen" / "rom_offsets.c"


def parse_segments(yaml_path):
    """Parse splat.yaml and extract all named segments with ROM start addresses."""
    with open(yaml_path, "r") as f:
        data = yaml.safe_load(f)

    segments = []
    for seg in data.get("segments", []):
        if isinstance(seg, dict) and "start" in seg:
            # Named segment block. Symbol name comes from 'name' field, or
            # 'dir' field with slashes replaced by underscores (splat convention).
            name = seg.get("name")
            if not name:
                name = seg.get("dir", "").replace("/", "_")
            if name:
                segments.append((name, seg["start"]))
        elif isinstance(seg, list) and len(seg) >= 3:
            # Inline segment: [rom_addr, type, name, ...]
            if isinstance(seg[0], int) and isinstance(seg[2], str):
                # Normalize name: "title/bg_1" -> "title_bg_1"
                name = seg[2].replace("/", "_")
                segments.append((name, seg[0]))

    # Add aliases for segments whose overlay_stubs name differs from yaml name
    alias_map = {
        "obfuscation_shims": "obfuscated_obfuscation_shims",
        "sprite_shading_profiles": "sprite_shading_profiles_data",
    }
    aliases = []
    for name, addr in segments:
        if name in alias_map:
            aliases.append((alias_map[name], addr))
    segments.extend(aliases)

    return segments


def compute_rom_ends(segments):
    """Compute ROM_END for each segment.

    For non-overlapping segments, ROM_END = next segment's ROM_START.
    For overlapping segments (shared ROM start), all get the same ROM_END
    (the next unique ROM address). This matches N64 overlay behavior where
    the overlay block is sized for the largest overlay in the group.
    """
    # Collect all unique ROM start addresses in order
    unique_starts = sorted(set(addr for _, addr in segments))

    # Map each start address to its end (= next unique start)
    start_to_end = {}
    for i, addr in enumerate(unique_starts):
        if i + 1 < len(unique_starts):
            start_to_end[addr] = unique_starts[i + 1]
        else:
            # Last segment: use a reasonable ROM size (40MB for PM US)
            start_to_end[addr] = 0x2800000

    # Build result: (name, rom_start, rom_end) for each segment
    result = []
    for name, start in segments:
        end = start_to_end[start]
        result.append((name, start, end))

    return result


def get_existing_stub_symbols(stubs_path):
    """Read overlay_stubs.c and return the set of full symbol names (e.g.,
    'logos_ROM_START', 'logos_ROM_END') that have stub definitions."""
    symbols = set()
    import re
    with open(stubs_path, "r") as f:
        for line in f:
            m = re.match(r"u8\s+(\w+_ROM_(?:START|END))\s*=", line)
            if m:
                symbols.add(m.group(1))
    return symbols


def generate_c_file(segments, output_path, existing_syms):
    """Generate rom_offsets.c with the lookup table.

    Only includes entries whose symbol names exist in existing_syms
    (from overlay_stubs.c), to avoid undefined reference linker errors.
    """

    # Sort by name for deterministic output
    segments.sort(key=lambda x: x[0])

    # Build list of (symbol_name, rom_offset) entries, filtered
    entries = []
    for name, start, end in segments:
        start_sym = f"{name}_ROM_START"
        end_sym = f"{name}_ROM_END"
        if start_sym in existing_syms:
            entries.append((start_sym, start))
        if end_sym in existing_syms:
            entries.append((end_sym, end))

    lines = []
    lines.append("/**")
    lines.append(" * rom_offsets.c - Auto-generated ROM offset lookup table")
    lines.append(" *")
    lines.append(" * Maps overlay stub symbol addresses to baserom.z64 file offsets.")
    lines.append(" * Generated by tools/pc/gen_rom_offsets.py from ver/us/splat.yaml.")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "common.h"')
    lines.append('#include <stddef.h>')
    lines.append("")
    lines.append("// Forward declarations of stub symbols referenced in the table")

    syms_used = sorted(set(sym for sym, _ in entries))
    for sym in syms_used:
        lines.append(f"extern u8 {sym};")

    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const void* symbol_addr;")
    lines.append("    u32 rom_offset;")
    lines.append("} RomSymbolEntry;")
    lines.append("")
    lines.append("// Table is sorted by symbol_addr at runtime (qsort on first use).")
    lines.append(f"RomSymbolEntry gRomOffsetTable[] = {{")

    for sym, offset in entries:
        lines.append(f"    {{ &{sym}, 0x{offset:06X} }},")

    lines.append("};")
    lines.append(f"const u32 gRomOffsetTableSize = sizeof(gRomOffsetTable) / sizeof(gRomOffsetTable[0]);")
    lines.append("")

    os.makedirs(output_path.parent, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  {len(entries)} entries ({len(syms_used)} unique symbols)")


def main():
    if not SPLAT_YAML.exists():
        print(f"Error: {SPLAT_YAML} not found", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing {SPLAT_YAML}...")
    segments = parse_segments(SPLAT_YAML)
    print(f"  Found {len(segments)} named segments")

    segments_with_ends = compute_rom_ends(segments)

    # Only include entries for symbols that actually exist in overlay_stubs.c.
    # This avoids undefined reference errors for segments the game never DMA's.
    existing_syms = get_existing_stub_symbols(OVERLAY_STUBS)

    count = generate_c_file(segments_with_ends, OUTPUT_FILE, existing_syms)
    print(f"  Generated {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
